parameters:
  bonus_spells:
    0: [0,0,0,0,0,0,0,0,0,0]
    1: [0,1,0,0,0,0,0,0,0,0]
    2: [0,1,1,0,0,0,0,0,0,0]
    3: [0,1,1,1,0,0,0,0,0,0]
    4: [0,1,1,1,1,0,0,0,0,0]
    5: [0,2,1,1,1,1,0,0,0,0]
    6: [0,2,2,1,1,1,1,0,0,0]
    7: [0,2,2,2,1,1,1,1,0,0]
    8: [0,2,2,2,2,1,1,1,1,0]
    9: [0,3,2,2,2,2,1,1,1,1]
    10: [0,3,3,2,2,2,2,1,1,1]
    11: [0,3,3,3,2,2,2,2,1,1]
    12: [0,3,3,3,3,2,2,2,2,1]
    13: [0,4,3,3,3,3,2,2,2,2]
    14: [0,4,4,3,3,3,3,2,2,2]
    15: [0,4,4,4,3,3,3,3,2,2]
    16: [0,4,4,4,4,3,3,3,3,2]
    17: [0,5,4,4,4,4,3,3,3,3]
